language: ruby
rvm: 2.2
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y checkstyle
install: 
  - "gem install overcommit"
script: 
  - git config --global user.name "Fluid LA"
  - git config --global user.email "fluidtest@la.com"
  - "overcommit --sign"
  - "overcommit --sign pre-commit"
  - "cd main"
  - "overcommit --run"
