language: python
python:
  - "2.7"
sudo: required
install:
  - "pip install pre-commit"
  - sudo apt-get install -y simhash
script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_REPO_SLUG
  - git status
  - git diff-tree --no-commit-id --name-only -r master
  - git diff --name-only --diff-filter=AM HEAD...master
