language: java
rvm: ruby 2.2
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y checkstyle
install: 
  - "gem install overcommit"
before_script:
  - git config --global user.name "Fluid LA"
  - git config --global user.email "fluidtest@la.com"
  - overcommit --sign
  - overcommit --sign pre-commit
script: 
  - cd main
  - git add .
  - git commit -m "Test this"
