language: python
python:
  - "2.7"
sudo: required
install:
  - "pip install pre-commit"
  - sudo apt-get install -y simhash
script:
  - echo $TRAVIS_COMMIT_RANGE
  - git diff-tree --no-commit-id --name-only -r $TRAVIS_COMMIT
